### ISSUE TITLE
reflector going OOM caused by spiky behaviour

### ISSUE THREAD

**Issue by aeimer** [emberstack/kubernetes-reflector#187]
Hi guys,

my reflector pod just exited hard due to an out-of-memory event.
There are also regular errors popping up in the log.

Instana event:
![grafik](https://user-images.githubusercontent.com/25035182/120332773-5ab95600-c2ef-11eb-9571-28589dd1f012.png)

Instana pod details:
![grafik](https://user-images.githubusercontent.com/25035182/120332905-76bcf780-c2ef-11eb-985d-716a4b96749f.png)

Logs:
![grafik](https://user-images.githubusercontent.com/25035182/120332941-80465f80-c2ef-11eb-9ff1-d06a1f070b56.png)

These kind of logs repeat every few hours.

So one thing that came up, maybe the pod just needs more RAM than you specified here: https://github.com/emberstack/kubernetes-reflector/blob/master/src/helm/reflector/values.yaml#L58
But in general this works quite good, but I don't know where the spikes come from.
I have the second smaller cluster with reflector running, the RAM fills up there also, but not that fast and I couldn't see any OOMs so far.

Thank you for helping.

BR
Alex

**Comment by aeimer** [comment]
@winromulus can you have a look into? What can I do about it?

**Comment by scarby** [comment]
@aeimer Are you using the reflector to reflect certificates from LetsEncrypt?

**Comment by aeimer** [comment]
@scarby Yes, I actually do. Maybe #191 is the cause for this issue. Good point.

**Comment by aeimer** [comment]
@klimisa is there any chance that you can have a look into this issue?

**Comment by brokenjacobs** [comment]
Is the issue just the memory limit? Or is there some larger issue at play here causing a problem?

**Comment by aeimer** [comment]
@brokenjacobs AFAIK everyhting seems to work. We have cert-manager with LE running.

**Comment by aeimer** [comment]
no stale. Problem seems to persist
