### ISSUE TITLE
Settings for more frequent resources checks

### ISSUE THREAD

**Issue by sdurrheimer** [emberstack/kubernetes-reflector#243]
Hello,

First of all, thank you for this piece of tech, the `cert-manager` support is awesome.

Is there a setting/ENVVARs that would let us change the Watcher timer for more frequent resources checks?
We have temporary testing environments spawn in our cluster with dedicated namespaces. Sometimes we are hitting a long delay before the reflector picks up the new namespace for secrets mirroring if the watcher did run right before the new namespace is created.

**Comment by winromulus** [comment]
Hi @sdurrheimer 

The watchers are instant (react as soon as as a new event is pushed by k8s API server). There's no polling going on.
If you get a delay, that means that k8s pushed the event out late or the watcher is idling (known k8s bug, see #239 )
What version of k8s are you running on?

**Comment by sdurrheimer** [comment]
We are running k8s 1.19 right now.

**Comment by winromulus** [comment]
Yup, read #239

**Comment by sdurrheimer** [comment]
Thank you for your answer.
I wasn't aware the watcher was instant, so didn't think we were hitting the same issue as the one you linked.
Closing this one then.
