### ISSUE TITLE
Could not update - source does not permit it after upgrade to 6.x

### ISSUE THREAD

**Issue by dbpolito** [emberstack/kubernetes-reflector#244]
Seeing a lot of these logs now:

```
2021-12-17 19:57:55.703 +00:00 [WRN] (ES.Kubernetes.Reflector.Core.SecretMirror) Could not update dev-xxxx/xxx-tls - Source reflector/xxx-tls does not permit it.
```

Interesting that the annotation looks like:

```
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "(dev|staging|prod)-[a-zA-Z0-9-_]+"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "(dev|staging|prod)-[a-zA-Z0-9-_]+"
```

and the namespace is called `dev-...`

Another interesting fact is that it does work when creating new namespaces (it properly created the secrets)... it seems to sync, but on its scheduler / cron it fails for the existing ones.

**Comment by winromulus** [comment]
@dbpolito - are those the annotations on the source?
Can you provide an example of exact namespace names and how you defined the source so I can try to reproduce it?
No data from the secret is needed, just the definition.

**Comment by dbpolito** [comment]
Sure:

this is the source:

```
Name:         kool-deploy-tls
Namespace:    reflector
Labels:       <none>
Annotations:  cert-manager.io/alt-names: *.kool.dev
              cert-manager.io/certificate-name: kool-deploy-tls
              cert-manager.io/common-name: *.kool.dev
              cert-manager.io/ip-sans:
              cert-manager.io/issuer-group: cert-manager.io
              cert-manager.io/issuer-kind: ClusterIssuer
              cert-manager.io/issuer-name: acme
              cert-manager.io/uri-sans:
              reflector.v1.k8s.emberstack.com/reflection-allowed: true
              reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: (kool|dev|staging|prod)-[a-zA-Z0-9-_]+
              reflector.v1.k8s.emberstack.com/reflection-auto-enabled: true
              reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: (kool|dev|staging|prod)-[a-zA-Z0-9-_]+

Type:  kubernetes.io/tls
```

This is the other secret that is not syncing anymore:

```
Name:         kool-deploy-tls
Namespace:    dev-none-default-bioreligare-bioreligare-web-developkooldev
Labels:       <none>
Annotations:  reflector.v1.k8s.emberstack.com/auto-reflects: reflector/kool-deploy-tls
              reflector.v1.k8s.emberstack.com/reflected-at: "2021-11-25T14:40:16.8485358+00:00"
              reflector.v1.k8s.emberstack.com/reflected-version: 309208480
              reflector.v1.k8s.emberstack.com/reflects: reflector/kool-deploy-tls
```

**Comment by winromulus** [comment]
Thanks for supplying this. I'm in the middle of moving and don't have my dev cluster up. I'll try to set it up during the weekend to try to reproduce this.

**Comment by winromulus** [comment]
Hi @dbpolito 
I tried to reproduce the issue you're facing but I can't get the same results:
```
2021-12-19 17:29:08.290 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created dev-none-default-bioreligare-bioreligare-web-developkooldev/source-secret as a reflection of default/source-secret
2021-12-19 17:29:13.619 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:30.0144711. Faulted: False.
2021-12-19 17:29:13.620 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2021-12-19 17:29:15.074 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected default/source-secret where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2021-12-19 17:29:43.633 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:30.0127478. Faulted: False.
2021-12-19 17:29:43.635 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2021-12-19 17:29:45.131 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected default/source-secret where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
2021-12-19 17:30:13.647 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:30.0122199. Faulted: False.
2021-12-19 17:30:13.650 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2021-12-19 17:30:14.969 +02:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected default/source-secret where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 3.
```

The above are the logs from the reflector since the namespace creation. I set the watcher timeout to 30 seconds to it re-subscribes faster but all pans out.
I think you might have an issue either in regex allowed or something is different on your environment.
Can you try deleting the out-of-sync secrets and see if reflector recreates them?

**Comment by schwajo** [comment]
Hi,
I'm having this error too, but I think, that's not related to any annotation of secrets. It's an error (typo) in line 222 of file [ResourceMirror.cs](https://github.com/emberstack/kubernetes-reflector/blob/main/src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs#L222)
Instead
`   var source = await TryResourceGet(resourceRef);`
you have to do
`   var source = await TryResourceGet(sourceRef);`
because you want the the source object.
I don't have the possibility to compile and test myself, so I can only drop a hint here.

**Comment by winromulus** [comment]
@schwajo I think you might be right
If you're facing the same issue, can you create a small sample that reproduces it? It's much easier to hit this if I can correctly reproduce the problem.
I'm going to test this during the weekend (my dev environment is currently down).

**Comment by schwajo** [comment]
That's relatively easy. Generate a source secret and multipe reflected secrets and restart the reflector pod - the messages show up in the logs. Here my yamls:
`
apiVersion: v1
data:
  test: ""
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
  name: a
  namespace: default
---
apiVersion: v1
data:
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflected-version: "0"
    reflector.v1.k8s.emberstack.com/reflects: default/a
  name: b
  namespace: default
---
apiVersion: v1
data:
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflected-version: "0"
    reflector.v1.k8s.emberstack.com/reflects: default/a
  name: c
  namespace: default
---
apiVersion: v1
data:
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflected-version: "0"
    reflector.v1.k8s.emberstack.com/reflects: default/a
  name: d
  namespace: default
`
After restart of reflector pod, interestingly, not all secrets are affected in the logs and it's not deterministic reproducible.
`
[WRN] (ES.Kubernetes.Reflector.Core.SecretMirror) Could not update default/c - Source default/a does not permit it.
`
