### ISSUE TITLE
Any workarounds for #246 Reflector late updates on Kubernetes 1.20 and older (known bug on k8s)?

### ISSUE THREAD

**Issue by pmorch** [emberstack/kubernetes-reflector#248]
I understand that #246 "Reflector late updates on Kubernetes 1.20 and older (known bug on k8s)" isn't something you'll fix. But we're stuck on 1.20 (and older) and upgrading is not yet an option due to internal politics outside my control. Now the question is what workarounds that are possible. At least this works for me:

    kubectl -n kubernetes-reflector rollout restart deployment/kubernetes-reflector

but that seems like a sledgehammer, and I'm not sure what interval to restart with.

Are there other possible workarounds? If not, could someone help determine a "good" interval to restart the reflector with?

(Our cluster isn't actually that large: 40 namespaces, 254 secrets and 80 configmaps)

My only alternative is to not use kubernetes-reflector :-(

If you really don't want to deal with this and upgrading really is the only option, feel free to close this issue, but then please upgrade the prerequisite kubernetes version:

```diff
diff --git a/README.md b/README.md
index 9d9f741..7c0debf 100644
--- a/README.md
+++ b/README.md
@@ -18,7 +18,7 @@ If you need help or found a bug, please feel free to open an Issue on GitHub (ht
 Reflector can be deployed either manually or using Helm (recommended).
 
 ### Prerequisites
-- Kubernetes 1.14+
+- Kubernetes 1.21+
 - Helm 3 (if deployed using Helm)
 
 #### Deployment using Helm
```

**Comment by winromulus** [comment]
Hi

Did some Xmas coding, please see workaround posted in #246 available in version 6.1.16. Please note that this was the only workaround I could think of and with your cluster size it should be okay.

I'm going to close this issue pending discussion in #246
