### ISSUE TITLE
Consider pushing container images to Github Container Registry (GHCR)

### ISSUE THREAD

**Issue by onedr0p** [emberstack/kubernetes-reflector#250]
Hello,

In order to combat dockerhub's imposed rate limits it would be great too push your Docker images on GHCR as well as dockerhub. It should be a minimal change to push the images to ghcr as it's supported across all GitHub repositories for free.

Thanks!

**Comment by winromulus** [comment]
@onedr0p - planned but thanks for bringing it up.
I'm scheduling this for the next release.

**Comment by onedr0p** [comment]
Not stale

**Comment by onedr0p** [comment]
Not stale, any update @winromulus ? Thanks.

**Comment by winromulus** [comment]
@onedr0p still in progress. Did not have yet time for it :(
But it is something desired

**Comment by onedr0p** [comment]
Hi

**Comment by onedr0p** [comment]
I've replaced the need to use reflector with kyverno which also does a lot more. I'm going to close this issue as it doesn't seem like something the maintainer cares about or has time to do.
