### ISSUE TITLE
How does one trigger reflection other than the "auto" mechanism?

### ISSUE THREAD

**Issue by andrewsharpe** [emberstack/kubernetes-reflector#271]
https://github.com/EmberStack/kubernetes-reflector#automatic-mirror-creation

This works as it says on the tin, and the wording also implies there's an alternate "manual" method for reflection/mirroring.

I'm just wondering how I would trigger mirroring of something _without_ using the "auto" mechanism?

**Comment by winromulus** [comment]
Hi @andrewsharpe 

Apart from auto, you can manually indicate which new secret reflects a source secret. Have a look at the README as  there is an example on how to accomplish this using annotations (indicating the source).
