### ISSUE TITLE
[Question] Supporting older K8s versions and `apiextensions`

### ISSUE THREAD

**Issue by aspring** [emberstack/kubernetes-reflector#29]
Currently running on the latest EKS in Amazon (1.15) which is 1 version before the release of `apiextensions.k8s.io/v1`.  Is there a possibility of adding support for `apiextensions.k8s.io/v1beta1` until EKS is able to release its support for 1.16?

**Comment by winromulus** [comment]
Hi,
Okay there are quite a bit of questions regarding your setup but:
- If you have `cert-manager` version `0.11.0` and above, please try the latest release of reflector. It should work (pick up both v1beta1 and v1 of apiextensions. Untested but if memory serves right, it should work.
- If you have `cert-manager` version older than `0.11.0`  try `v2.19193.2` of reflector or older versions. That's the last version that I remember having support for `v1beta1`.

Please let me know what your findings are. I think the first option will work as long as you have an up to date version of `cert-manager`.

After you run the latested, make sure you run with Debug level and post your logs here (for each version tried). I might come up with a quick fix for you.

**Comment by aspring** [comment]
Currently running `cert-manager 0.14.1` and `reflector 4.1.12` and upon startup reflector is logging the following:

```
[INF] (ES.Kubernetes.Reflector.Host.Program) Starting host
[DBG] (ES.Kubernetes.Reflector.Core.CoreModule) Building client configuration. Client is in cluster: 'True'
[DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Starting
[DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Started
[DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Starting
[DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Started
[ERR] (ES.Kubernetes.Reflector.Secrets.FortiMirror) Current kubernetes version does not support CustomResourceDefinition apiVersion v1.
[DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1ConfigMap watcher Starting
[DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1ConfigMap watcher Started
[DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1Namespace watcher Starting
[DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1Namespace watcher Started
[ERR] (ES.Kubernetes.Reflector.CertManager.Monitor) Current kubernetes version does not support CustomResourceDefinition apiVersion v1.
```
Ive annotated existing and new certs with the following:
```
annotations:
  reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
  reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
```

The certificates are issued by cert-manager and the secrets for them properly hydrated, however, the reflector annotations are not present in the resulting secret nor are the mirror secrets created.

**Comment by winromulus** [comment]
Can you uninstall reflector and install version `v2.19193.2` please and try it again?
(also include logs please)

**Comment by aspring** [comment]
Ive uninstalled and installed with that version and got the output below.  Also, as a sanity check Ive added a regular Secret with annotations which does work and is reflected properly which is referenced in the output.

```
Helm Chart:             4.1.12  (To pull in cert-manager apigroup RBAC)
Reflector Version:      emberstack/es.kubernetes.reflector:release-2.19193.2
Certificate apiVersion: cert-manager.io/v1alpha3

13:33:04.199 +00:00 [INF] () Host starting
13:33:04.358 +00:00 [INF] (ES.Kubernetes.Reflector.Startup) CertManager extension enabled: True
13:33:04.717 +00:00 [DBG] (ES.Kubernetes.Reflector.Core.CoreModule) Building client configuration. Client is in cluster: 'True'
13:33:04.868 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Starting
13:33:05.126 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Started
13:33:05.128 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Starting
13:33:05.168 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Started
13:33:05.173 +00:00 [DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1ConfigMap watcher Starting
13:33:05.206 +00:00 [DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1ConfigMap watcher Started
13:33:05.206 +00:00 [DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1Namespace watcher Starting
13:33:05.218 +00:00 [DBG] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1Namespace watcher Started
13:33:05.234 +00:00 [DBG] (ES.Kubernetes.Reflector.CertManager.Monitor) V1beta1CustomResourceDefinition watcher Starting
13:33:05.278 +00:00 [DBG] (ES.Kubernetes.Reflector.CertManager.Monitor) V1beta1CustomResourceDefinition watcher Started
13:33:06.501 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) Secret cert-manager/cloudflare-api-token reflected version (2207346) matches source kube-system/cloudflare-api-token version (2207346)
13:33:09.704 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) Secret cert-manager/cloudflare-api-token reflected version (2207346) matches source kube-system/cloudflare-api-token version (2207346)```

**Comment by winromulus** [comment]
@aspring problem is that cert-manager had a different CRD namespace in that version (they moved to cert-manager.io later).
I'll try to reproduce the issue.
Please confirm the following as a target:
Kubernetes version: 1.15
Reflector: 4.1.12
Cert-Manager: 0.14.1

Once you confirm, I'll create a test cluster somewhere (probably Azure) and install them and see if I can support the older version.

**Comment by aspring** [comment]
I can confirm those are the versions.

**Comment by winromulus** [comment]
@aspring Confirmed the issue. Working on a possible fix.
I'm going to create a Slack organization and send you an invite link to debug once I have a solution to this.

**Comment by winromulus** [comment]
@aspring please join our Slack so we can debug further:
https://join.slack.com/t/emberstack/shared_invite/zt-8qyutopg-9ghwTq3OnHSm2tY9Sk5ULA

**Comment by sc250024** [comment]
@winromulus @aspring Having the same issue. Let me know if you need help.

**Comment by winromulus** [comment]
@sc250024 join our Slack please (link above) for debugging
currently working on trying to support this
