### ISSUE TITLE
Reflector keeps deleting manually mirrored secrets

### ISSUE THREAD

**Issue by mateuszdrab** [emberstack/kubernetes-reflector#295]
I have an issue with reflector where after applying a mirror secret, it will get reflected correctly and then deleted later. I traced the event in the log but I do not understand why this happens.

Log states:
`2022-07-11 20:16:20.993 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected xxx where permitted. Created 0 - Updated 0 - Deleted 2 - Validated 3.`

The source secret has the following annotations:
```
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: some-namespaces
```

The secret is auto-reflected perfectly, the deletion behavior only affects manual mirrors. What am I doing wrong?

Thanks

**Comment by winromulus** [comment]
Please try the new version. This issue should be fixed. Please reopen if this is still a problem (some scenarios are extremely hard to reproduce and help is required to validate the fix).
