### ISSUE TITLE
New replicaset of reflector deployment getting created in every 5 mins (approx.) mystically

### ISSUE THREAD

**Issue by udhanMti** [emberstack/kubernetes-reflector#301]
Hi guys,

We are using reflector in our cluster for some time.

reflector version - 5.4.17
Kubernetes version - 1.22

Since two days ago, we are observing that new replica sets getting created in the reflector deployment in every 5 mins (approx.) mystically.

The following events can be seen when we describe one of the replica sets.
```
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  32m   replicaset-controller  Created pod: reflector-fbdd5f4f-wjgpk
  Normal  SuccessfulDelete  27m   replicaset-controller  Deleted pod: reflector-fbdd5f4f-wjgpk
```

The following events can be seen when we describe the deployment.

```
Events:
  Type    Reason             Age                    From                   Message
  ----    ------             ----                   ----                   -------
  Normal  ScalingReplicaSet  2m36s (x681 over 28h)  deployment-controller  (combined from similar events): Scaled down replica set reflector-6cf8b964f9 to 0
```

Is there any way we can find the root cause or fix this issue?

Best regards
Udhan

**Comment by winromulus** [comment]
This seems to be an auto-scaling issue in your environment. There's nothing for this configured in reflector (should always run as a single instance). This is not something I can help with.
