### ISSUE TITLE
[Enhancement] Add securityContext to helm chart

### ISSUE THREAD

**Issue by ajchiarello** [emberstack/kubernetes-reflector#31]
Can you add a block to the deployment template that would allow us to set the securityContext settings when installing the helm chart? Could look something like this:

    {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}

**Comment by winromulus** [comment]
Hi @ajchiarello I've assigned this enhancement to myself. I don't have enough spare cycles to tackle this now, but if you have time your can submit a PR for it.

**Comment by ajchiarello** [comment]
@winromulus I had time :)

**Comment by winromulus** [comment]
PR merged! Thank you for your contribution to this, very much appreciated!
