### ISSUE TITLE
[bug] Kubectl manifests refer to the wrong application version

### ISSUE THREAD

**Issue by sfynx** [emberstack/kubernetes-reflector#33]
I noticed that the `reflector.yaml` files always refer to `release-0.1.0` inside, no matter which release on GitHub they are bundled with. Is it intended that you need to change these yourself if you are not using the Helm chart?

**Comment by winromulus** [comment]
Hi,

No, that is a bug. Thanks for spotting it.

**Comment by winromulus** [comment]
@sfynx - This was fixed in version 5.0.x It should now use the correct application version
