### ISSUE TITLE
No way to add securityContext to cron container

### ISSUE THREAD

**Issue by MariusGrandeAndersen** [emberstack/kubernetes-reflector#336]
Issue:
Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [azurepolicy-k8sazurev3allowedusersgroups-57ac95e12d2c31538661] Container reflector-startupapicheck is attempting to run without a required securityContext/fsGroup. Allowed fsGroup: {"ranges": [{"max": 65535, "min": 1}], "rule": "MustRunAs"}

On the helm chart we have ability to add .Values.cron.securityContext, but we also need this on the container level.
Example on one of our own cronjobs that has this:
![image](https://user-images.githubusercontent.com/3061094/223448451-8c5630a9-f8f1-4534-99a5-fa4e257cdbe3.png)

**Comment by winromulus** [comment]
Hi @MariusGrandeAndersen thanks for submitting this. Any PR for this would be great.
Maybe  @idrissneumann can enhance this since the work on the cron container was done by him.

**Comment by MariusGrandeAndersen** [comment]
sorry this issue is not in your chart, I have a quite complex helmchart of dependencies and it's a cert-manager thing, sorry for the waste of time
