### ISSUE TITLE
System.IO.IOException: The request was aborted with 7.0.151

### ISSUE THREAD

**Issue by xakraz** [emberstack/kubernetes-reflector#345]
Hi there 👋🏻 

# Context

* We have created a "brand new" GKE cluster (`v1.23.16-gke.1400`)
* We have deployed the latest release of `kubernetes-reflector` via Helm (`7.0.151`)

The pod sometime just stop doing anything or throw the following errors

```
[ERR] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Faulted due to exception.
System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer
---> System.Net.Sockets.SocketException (104): Connection reset by peer
```

## ConfigMapWatcher

![image](https://user-images.githubusercontent.com/1590399/230352423-ccda54ea-43bb-4be6-b5ed-fe1b9405cc67.png)

## SecretWatcher

![image](https://user-images.githubusercontent.com/1590399/230352532-41d6f92c-7951-4187-a33b-48ba594df205.png)

## NamespaceWatcher

![image](https://user-images.githubusercontent.com/1590399/230352798-33e49451-4613-47c2-a81a-f3a658b1df73.png)

# Workaround

We had another GKE cluster also in 1.23.16 with  `kubernetes-reflector` version `5.4.17` that seems to work without that issue.
-> We deployed this version in the new cluster and it "works" as expected.

We would like to be able to deploy the latest version of `kubernetes-reflector` and especially since it is a brand new cluster 🙃

**Comment by winromulus** [comment]
This should be fixed in the latest version. Reopen please if this problem still appears
