### ISSUE TITLE
Helm cron job old resource api

### ISSUE THREAD

**Issue by tobiasz-gleba** [emberstack/kubernetes-reflector#362]
```
Helm upgrade failed: resource mapping not found for name: "reflector" namespace: "reflector" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first
```
Currently the api is `apiVersion: batch/v1`, but helm chart uses the old api version. Can we update that?

**Comment by sydorovdmytro** [comment]
Have you tried to specify it in values.yaml? 
https://github.com/emberstack/kubernetes-reflector/blob/main/src/helm/reflector/templates/cron.yaml#L3

**Comment by tobiasz-gleba** [comment]
No, it is not mentioned in the documentation or [values file](https://github.com/emberstack/kubernetes-reflector/blob/main/src/helm/reflector/values.yaml). 

Indeed in code there is such option, thank you
