### ISSUE TITLE
kubectl apply -f doesn't work

### ISSUE THREAD

**Issue by antonioluzzi** [emberstack/kubernetes-reflector#369]
Hi,
I'm trying to install the reflector without success on my k8s cluster (v1.27.4).
When I use the following command:

_kubectl -n kube-system apply -f  https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml_

I'll get:
_the namespace from the provided object "default" does not match the namespace "kube-system". You must pass '--namespace=default' to perform this operation._

I can install only in the default namespace, but It doesn't work when I deploy my secret with the following annotation:
     reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
     reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "dev-1,dev-2,dev-[0-9]*"

**Comment by antonioluzzi** [comment]
I have solved to modify yaml file:

`apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-7.0.193
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "7.0.193"
    app.kubernetes.io/managed-by: Helm
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-7.0.193
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "7.0.193"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["watch", "list"]
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-7.0.193
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "7.0.193"
    app.kubernetes.io/managed-by: Helm
roleRef:
  kind: ClusterRole
  name: reflector
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: reflector
    namespace: kube-system
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-7.0.193
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "7.0.193"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflector
      app.kubernetes.io/instance: reflector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reflector
        app.kubernetes.io/instance: reflector
    spec:
      serviceAccountName: reflector
      securityContext:
        fsGroup: 2000
      containers:
        - name: reflector
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
          image: "emberstack/kubernetes-reflector:7.0.193"
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_Serilog__MinimumLevel__Default
              value: "Information"
            - name: ES_Reflector__Watcher__Timeout
              value: ""
          ports:
            - name: http
              containerPort: 25080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {}
`

**Comment by sh-cho** [comment]
```sh
$ wget -q -O - https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml \
   | sed -E 's/([[:space:]]*namespace:[[:space:]]*)default/\1kube-system/' \
   | kubectl -n kube-system apply -f -
```
Same here. Just workaround here

```sh
$ wget -q -O - https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml \
   | sed -E 's/([[:space:]]*namespace:[[:space:]]*)default/\1kube-system/' \
   | kubectl -n kube-system apply --dry-run=client -f -
```
Check with dry-run
