### ISSUE TITLE
Attempted to replicate a resource to terminated namespace

### ISSUE THREAD

**Issue by k0dep** [emberstack/kubernetes-reflector#38]
if namespace is in Terminated status, reflector still process resources for this namespace.
When it happens, reflector make restart watches and come to infinity loop with errors.

**Comment by winromulus** [comment]
@k0dep can you provide me a small sample of the logs please?
The replication needs to warn in that scenario and skip the namespace.
If you want you can join our slack (link in README) and you can share those privately.
To be procise:
- I need the first exception that occurs from the logs

**Comment by winromulus** [comment]
I assume this issue is no longer a problem and am closing the issue.
Feel free to reopen if needed.
