### ISSUE TITLE
[Question]readOnlyRootFilesystem

### ISSUE THREAD

**Issue by zoltan-keller** [emberstack/kubernetes-reflector#381]
Hi,

wanted to ask on the [readOnlyRootFilesystem=false](https://github.com/emberstack/kubernetes-reflector/blob/0134c897407e2e0f87a618afabf5baa6791b299a/src/helm/reflector/values.yaml#L59) setting in the helm chart. What is the specific reason behind this setting? Tried to run it with read only root fs enabled but the pod immediately crashes. 

br.

Zoltan

**Comment by winromulus** [comment]
@zoltan-keller dotnet cannot run with a readOnlyRootFilesystem since it requires temporary files. I will re-test this with dotnet 8 as part of the hardening effort

**Comment by pareion** [comment]
You can configure the application to write it to a specific path, then specify an emptyDir volume so it can manipulate files inside the directory, but not in the entire filesystem.

Requesting to add support for this and reopen the suggestion.
