### ISSUE TITLE
Why does reflector need to list/watch CRDs?

### ISSUE THREAD

**Issue by sdimovv** [emberstack/kubernetes-reflector#382]
This is probably a stupid question but why does Reflector need this role:

https://github.com/emberstack/kubernetes-reflector/blob/0134c897407e2e0f87a618afabf5baa6791b299a/src/helm/reflector/templates/clusterRole.yaml#L16-L18

**Comment by winromulus** [comment]
@sdimovv these were used for the cert-manager plugin which was deprecated and these need to be removed. Pushed a change a few moments ago to remove them.

**Comment by winromulus** [comment]
Issue solved
