### ISSUE TITLE
[Question/Support] Reflector hangs at startup with "Requesting resources"..

### ISSUE THREAD

**Issue by tijnster** [emberstack/kubernetes-reflector#383]
Hi,

During startup the Reflector pod hangs at startup with requesting resources from namespaces, configmaps and secrets.

<img width="1381" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/34685850/b2be5d9b-c5fb-4e1c-9feb-9f0b7dd74b8d">

I thought it was due relation to the kube api server not being able to communicate from within the pod, but I tried testing the connection with curl from a pod on the worker node and I can reach the kube api server just fine. Any thoughts on this?

**Comment by winromulus** [comment]
@tijnster this situation is very odd, especially if you tried to curl from the worker node to the API server and it's responding with resources.
Please provide more information about your setup: kube version and setup type (is this vanilla k8s or k3s or something else), hosting type (on prem vs cloud).

**Comment by tijnster** [comment]
@winromulus 
Sure. I'm running it in my homelab, I installed vanilla k8s with Ansible. I'm running proxmox as virtualisation software. I'm using version 1.23.6-00 for kubelet, kubeadm and kubectl. I'm mainly using manifests for deployments, although I Reflector is installed with Helm. 

So I tried curling from a pod to kube-api server, works like a charm. I also double checked if port 443 was open on the VM's (running ubuntu), with ufw status verbose and double checked with nmap. Do you need any more info?

**Comment by winromulus** [comment]
@tijnster can you exec into the pod please and try to curl from there (install if needed). Try to access the kube API server via the internal IP (not external). Try listing the namespaces using cURL but from within the pod.
This is really weird (I've never encountered this issue before) and the only thing I can think of is either network policy to the API server or something firewall related (on the mesh network).

**Comment by tijnster** [comment]
@winromulus 
I just tested it from a nginx pod (reflector pod won't allow me to install curl, there is no root available). Quering the API gave a valid response, however when listing namespaces I got an error, so nice catch.

  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "namespaces is forbidden: User \"system:serviceaccount:cert-manager:default\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "kind": "namespaces"
  },
  "code": 403
  
  
 I see that the reflector pod is using a service account named reflector, I can also list that in the cert-manager namespace (I'm also using the certmanager annotations with reflector). However, I don't see any rolebindings or roles dedicated to this service account. Should that be there? I can of course create a few myself, was just wondering what would be the best way to resolve this.

**Comment by tijnster** [comment]
@winromulus 
I used a nginx-pod in the cert-manager namespace because from within the reflector pod I was not able to install curl. However, I checked in the deployment of Reflector that it use a serviceaccount named "Reflector", which is bound to a clusterrole and clusterrolebinding, with all the acess it needs to list namespaces, and modify secrets and configmaps. So, for testing the listing of the namespaces from within the pod, I used that service account (I edited the nginx deployment and added serviceAccountName: reflector to it). Turns out I can list namespaces..

I double checked if my nginx test pod was using the correct service account by echo-ing the token and comparing it with the reflector service account token, and they match.

<img width="1512" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/34685850/56efd00d-e349-47a4-a27d-a4e684f87324">

Any other things I could try?

**Comment by winromulus** [comment]
@tijnster set reflector to log level Verbose and provide the logs please. I'm really confused why it can't hit the API server.

**Comment by tijnster** [comment]
@winromulus 
I did another test from the nginx pod to see if it also could list secrets in a namespace with the reflector service account and that also seemed to work with:
curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/kubernetes-dashboard/secrets

I redeployed the helm chart with configuration.logging.minimumLevel set to Verbose. It looks like it's hanging on a mirror with a configmap related to my ingress controller:

Beginning of the logging:
<img width="1740" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/34685850/9a70294e-9cab-4396-a40a-aeeb32e47860">

<img width="1740" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/34685850/b9f12212-c0bf-48c7-81c5-2e5d9d810c0b">

Part where it seems stuck:
<img width="1740" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/34685850/b749ae65-9c59-4411-9df3-2678fecc8b13">

**Comment by winromulus** [comment]
@tijnster Reflector seems to be working fine. It's not hanging on that config map, that configmap changes VERY often (since it's part of leader election).
Create a test secret and see if it reflects it properly

**Comment by tijnster** [comment]
@winromulus Ah, of course..
Funny enough it seems to be working fine now(?). My secrets are getting mirrored just fine.
<img width="1792" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/34685850/41a1d37a-d969-4d3a-a0b6-9580eecc6b57">

Thanks for putting in the time to help me out.

**Comment by winromulus** [comment]
No worries, glad it was sorted out.
