### ISSUE TITLE
Reflector giving customer resource definition related error on EKS 1.15

### ISSUE THREAD

**Issue by mukulgit123** [emberstack/kubernetes-reflector#41]
## When I deploy reflector, it gives below error when I deploy it on my cluster which I created using Terraform. I really would like to use this. Any help or hints given are much appreciated.

`2020-05-19 09:28:29.676 +00:00 [INF] (ES.Kubernetes.Reflector.Host.Program) Starting host
2020-05-19 09:28:30.475 +00:00 [WRN] (ES.Kubernetes.Reflector.CertManager.Monitor) Current kubernetes version does not support CustomResourceDefinition apiVersion v1.
`

### Source: reflector/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-5.0.10
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "5.0.10"
    app.kubernetes.io/managed-by: Helm

### Source: reflector/templates/clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
  labels:
    helm.sh/chart: reflector-5.0.10
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "5.0.10"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["watch", "list"]
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["watch", "list"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["watch", "list"]
---
### Source: reflector/templates/clusterRoleBinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector
  labels:
    helm.sh/chart: reflector-5.0.10
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "5.0.10"
    app.kubernetes.io/managed-by: Helm
roleRef:
  kind: ClusterRole
  name: reflector
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: reflector
    namespace: kube-system
---
### Source: reflector/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-5.0.10
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "5.0.10"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflector
      app.kubernetes.io/instance: reflector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reflector
        app.kubernetes.io/instance: reflector
    spec:
      serviceAccountName: reflector
      securityContext:
        fsGroup: 2000
      containers:
        - name: reflector
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
          image: "emberstack/kubernetes-reflector:5.0.10"
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_Serilog__MinimumLevel__Default
              value: "Information"
          ports:
            - name: http
              containerPort: 25080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http

**Comment by winromulus** [comment]
Hi @mukulgit123,
Reflector should work even without support for it. You can ignore that warning.
Are you planning to use it with cert-manager?

**Comment by mukulgit123** [comment]
@winromulus Thanks for your response. I am not planning to use it with cert-manager as of now. 

I tested it for one of the secrets on my dynamically created cluster and it worked fine. 

Earlier I had tested for configmap which didn't seem to work. I will test it again for configmap and will let you know. I Will close this issue once I test for configmap. 

Thanks!!

**Comment by winromulus** [comment]
I'm assuming this issue is no longer a problem.
If you continue to encounter issues, please reopen.
