### ISSUE TITLE
Reflector pod not able to start up

### ISSUE THREAD

**Issue by israelvaldez** [emberstack/kubernetes-reflector#426]
Suddenly the reflector pod is no longer running, it fails to start with no logs (pod logs) the only available logs are the kubernetes events of the pod, can you help us find a solution to this problem?

Reflector image tag is emberstack/kubernetes-reflector:7.1.262

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  12m                    default-scheduler  Successfully assigned reflector/reflector-7b97564cf4-9xgqg to aks-linuti-11695480-vmss00000a
  Normal   Killing    11m                    kubelet            Container reflector failed startup probe, will be restarted
  Normal   Pulled     11m (x2 over 12m)      kubelet            Container image "emberstack/kubernetes-reflector:7.1.262" already present on machine
  Normal   Created    11m (x2 over 12m)      kubelet            Created container reflector
  Normal   Started    11m (x2 over 11m)      kubelet            Started container reflector
  Warning  Unhealthy  7m3s (x53 over 11m)    kubelet            Startup probe failed: Get "http://10.7.5.70:25080/healthz": dial tcp 10.7.5.70:25080: connect: connection refused
  Warning  BackOff    116s (x16 over 5m32s)  kubelet            Back-off restarting failed container

**Comment by winromulus** [comment]
It seems like something is preventing the pod from listening on the port. Can you provide more details about your environment?

**Comment by winromulus** [comment]
I'm closing this ticket due to inactivity.
