### ISSUE TITLE
Change in Mirror Objects is Not Reflected

### ISSUE THREAD

**Issue by ashishp0911gmail** [emberstack/kubernetes-reflector#427]
Hello, 

This may not be an issue , rather I feel this could be the intended way it was designed in the first place , but would still like to highlight it.
On changing the Source Resource , the Mirror Resources get changed.

But , if I change the Mirror Resource , it does not replicate the changes. Would like to know if this is possible to ensure if any user changes the Mirror resource , it also triggers a change on the Source and other mirrors.

Thanks and Regards,
Ashish .A. Poojary

**Comment by winromulus** [comment]
Hi @ashishp0911gmail 
This works as intended. There is no two way mirroring from the destination to the source. The intent of the project is to propagate the source to multiple namespaces and ensure consistency (if the source is updated, the mirrors reflect that).
