### ISSUE TITLE
Session Closed

### ISSUE THREAD

**Issue by mshekharee** [emberstack/kubernetes-reflector#433]
Getting an info  : `(ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:35:04.2819442. Faulted: False.` from the pod. can someone please let us know if this would cause issues?

<img width="1347" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/70192286/4fb9d6a9-6aae-495d-a5fa-43cf5c1abf6e">

**Comment by winromulus** [comment]
@mshekharee that is fine. That's the timeout from k8s and reflector will just open a new connection. The average is around 45 mins.
