### ISSUE TITLE
possible to use wildcard?

### ISSUE THREAD

**Issue by dberardo-com** [emberstack/kubernetes-reflector#444]
is it possible to enable auto reflection in all namespaces matching a pattern? such as:

reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "important-guy-*"

to match all of "important-guy-robert","important-guy-max", etc ... ?

**Comment by winromulus** [comment]
@dberardo-com Use regex for allowed namespaces. This is more flexible than plain wildcards.

**Comment by dberardo-com** [comment]
i see, so you are saying to use:

```
reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "important-guy-*"
```
?

and is it regex or simple wildcard ?

**Comment by winromulus** [comment]
@dberardo-com It's RegEx. Please have a look at the readme
