### ISSUE TITLE
[Investigation] Possible memory leak

### ISSUE THREAD

**Issue by radarnex** [emberstack/kubernetes-reflector#63]
We use Reflector for the cert-manager secret replication feature. We suspect there is a memory leak because of the memory usage pattern. It happens on clusters with a few namespaces and others with hundreds.

K8s version: 1.16 (but it happend to us also in 1.15)
Reflector version: 5.0.10

![reflector mem usage](https://user-images.githubusercontent.com/15276213/88157712-689c4600-cc0b-11ea-8f66-c1c767d42b44.png)

**Comment by winromulus** [comment]
Hi @radarnex 
Can you tell me more about the environments please?
I.e. How many namespaces, how many secrets, how many namespace changes (create/delete).
Memory is used by the reflector when a namespace or secret changes (since it needs to re-index everything).

**Comment by radarnex** [comment]
Hi @winromulus 

We have two kinds of clusters:
- Normal density clusters: 10 namespaces, 2-3 secrets to replicate, no namespace changes after setup
- Heavy density clusters: 150-200 namespaces, 2-3 secrets to replicate, frequent namespaces changes (1-3 changes per hour)

The screenshot of the issue is from a normal cluster. Memory usage patterns on normal and heavy seems more or less the same.

BTW, Yesterday we upgraded to latest version `5.1.43` to see if the issue improves.

**Comment by winromulus** [comment]
@radarnex I'm still investigating this but it takes a long time to get some results. My suspicions are centered around the healtch checks or sporadic disconnects from the API server.

**Comment by winromulus** [comment]
@radarnex - please try version 5.2.2 and let me know if the issue improves.

**Comment by radarnex** [comment]
@winromulus Thank you, we'll give it a shot. BTW, since we upgraded to `5.1.43` the memory usage pattern seems much better in all clusters. The only relevant change I see is a `kubernetes-client` bump [on this commit](https://github.com/emberstack/kubernetes-reflector/commit/e865553cde83e41bd78c73201c16cae5ecd8600b).

![reflector mem usage after upgrade](https://user-images.githubusercontent.com/15276213/88559857-a9da8e80-d02d-11ea-982e-eeacdb03419b.png)

**Comment by winromulus** [comment]
@radarnex do you see an improvement?
