### ISSUE TITLE
[Enhancement] Reflector for Istio Gateway objects

### ISSUE THREAD

**Issue by dex4er** [emberstack/kubernetes-reflector#68]
Hi. I use Istio 1.6.5 in my cluster and I noticed that copying Cerificate objects to istio-system namespace is not enough for correct configuration. I need to copy additional Gateway object and it makes perfect sense: the gateway points to the certificate and its secret so it should be in istio-system namespace too.

Would it be possible to add the support for Gateway to Reflector?

Currently I had to switch back to the Helm charts without Reflector and set the namespace explicitly for Certificate and Gateway but I like idea of Reflector very much so I miss this feature badly.

**Comment by winromulus** [comment]
@dex4er I haven't used Istio before. Can you provide more details for the behavior?

**Comment by dex4er** [comment]
This is the description of the Gateway object: https://istio.io/latest/docs/reference/config/networking/gateway/

In practice: the Gateway and the Secret with TLS certificate (so Certificate too) should be in istio-system namespace where istio-ingressgateway service is started.

Gateway + VirtualService objects are alternative to the Ingress object for Istio. Actually you can convert Ingress to Gateway+VirtualService automatically but it has limited support for TLS so autoconvertion is not recommended.

**Comment by dex4er** [comment]
And cite from Gateway specification:

"In other words, the Gateway resource must reside in the same namespace as the gateway workload instance."

So if workload for Gateway resides in istio-system then I would need to create Gateway object there.

**Comment by winromulus** [comment]
@dex4er I'm still looking into this. The amount of effort is significant (especially since I've never used Istio). I'll keep it as a long-term goal.
