### ISSUE TITLE
(feat): Prometheus monitoring

### ISSUE THREAD

**Issue by lukasmrtvy** [emberstack/kubernetes-reflector#78]
Would be nice to have metrics endpoint for prometheus monitoring.

Use case:
- number of secrets handled by the kubernetes-reflector
- number of reflected secrets

Related: https://github.com/emberstack/kubernetes-reflector/issues/77

Thanks

**Comment by snuggie12** [comment]
Can this be re-opened?

**Comment by snuggie12** [comment]
Not sure if I can unstale this, but...bump?

**Comment by snuggie12** [comment]
Bumping to remove stale

**Comment by snuggie12** [comment]
Bumping to remove stale

**Comment by snuggie12** [comment]
Bumping to remove stale

**Comment by snuggie12** [comment]
Bumping to remove stale

**Comment by xbglowx** [comment]
Bump to remove stale.

**Comment by xbglowx** [comment]
This is a fun game to play.

**Comment by automaticgiant-ml** [comment]
could you please reopen this?
