### ISSUE TITLE
[Enhancement] Cert-manager ingress resources

### ISSUE THREAD

**Issue by tvvignesh** [emberstack/kubernetes-reflector#96]
Hi. I have setup Cert Manager to do TLS using this: https://cert-manager.io/docs/usage/ingress/ where I annotate the ingress and cert manager automatically creates the Certificate and secrets for me and it works well without issues.

Now, I wanted to mirror the created secret to different namespaces with reflector but I am not sure how to annotate an ingress resource with reflector (the README talks about the certificate resource).

Any ideas how I can achieve this cause the secret and certificate are being created automatically from ingress?

Thanks.

**Comment by winromulus** [comment]
@tvvignesh - Ingress resources are not supported for now. One thing you can do is use a certificate and point the ingress to the certificate's secret.

I'll give ingress resources another try this weekend. In the meantime you can use the above workaround.
